### PR TITLE
fix: add missing DELETE endpoint for skills

### LINKED ISSUE #223: Deleting skills doesn't seem to work
When adding a skill to the registry, I can list that skill, but deleting that skill returns a 404:

```bash
$ arctl skill list                                                                                                       1 ↵
NAME              TITLE   VERSION   CATEGORY   WEBSITE
git-commit                latest    <none>
repo-compliance           v0.1.0    <none>
$ arctl skill delete repo-compliance --version "v0.1.0"
Deleting skill repo-compliance version v0.1.0...
Error: failed to delete skill: unexpected status: 404 Not Found, {"detail":"Endpoint not found. See /docs for the API documentation.","status":404,"title":"Not Found"}
Usage:
  arctl skill delete <skill-name> [flags]

Flags:
  -h, --help             help for delete
      --version string   Specify the version to delete (required)

Global Flags:
      --registry-token string   Registry bearer token (overrides ARCTL_API_TOKEN)
      --registry-url string     Registry base URL (overrides ARCTL_API_BASE_URL; default http://localhost:12121)
  -v, --verbose                 Enable verbose output
```

### PR DESCRIPTION
**Pull request by optimus-fulcria**
# Description

Adds the missing `DELETE /v0/skills/{skillName}/versions/{version}` endpoint to the registry API.

**Motivation:** The `arctl skill delete` CLI command and client were already implemented, but the server had no corresponding endpoint, causing 404 errors.

**What changed:**
- Added DELETE handler in `internal/registry/api/handlers/v0/skills.go` with proper huma error codes (`huma.Error404NotFound`, `huma.Error401Unauthorized`, `huma.Error403Forbidden`)
- Added `DeleteSkill(ctx, tx, name, version)` to the database layer — deletes the skill row and promotes the next latest version in a transaction
- Added `DeleteSkill` to service interface and fake registry for testing
- Regenerated OpenAPI spec and TypeScript client
- Added e2e tests covering the full delete lifecycle

Fixes #223

# Change Type

/kind fix

# Changelog

```release-note
Add DELETE endpoint for removing skill versions from the registry
```

# Additional Notes

## Test plan
- [x] `go build ./...` passes
- [x] `go vet -tags e2e ./e2e/...` passes
- [x] E2e tests added in `e2e/skill_publish_test.go`:
  - `TestSkillDelete`: publish → verify exists → delete via CLI → confirm 404 → re-delete fails
  - `TestSkillDeletePromotesLatest`: publish v0.0.1 and v0.0.2 → verify latest is v0.0.2 → delete v0.0.2 → verify latest promoted to v0.0.1
  - `TestSkillDeleteNotFound`: HTTP DELETE on non-existent skill returns 404
- [x] Database deletion handles `is_latest` promotion in a transaction
- [x] Uses proper huma error codes (404, 401, 403) instead of generic errors

### CODE REVIEW

**Comment by peterj** [comment]
please update the PR template and add tests (probably e2e would make sense -- we have some skill tests already in the e2e folder)

**Comment by optimus-fulcria** [comment]
PR template updated. I'll add e2e tests - looking at the existing e2e/skill tests as a pattern.

**Comment by optimus-fulcria** [comment]
Both items addressed:
1. PR template updated.
2. E2e test added in 24d3b34 (`TestSkillDelete` in `skill_publish_test.go`): publishes a skill via `--github`, verifies 200, deletes via CLI, confirms 404.

**Comment by optimus-fulcria** [comment]
Done in 24d3b34: added `TestSkillDelete` e2e test that publishes a skill, verifies it exists, deletes it via the DELETE endpoint, then confirms 404.

**Comment by optimus-fulcria** [comment]
@peterj Updated per your feedback:

1. **PR template updated** - Body now follows the `.github/PULL_REQUEST_TEMPLATE.md` format with Description, Change Type, Changelog, and Test plan sections.

2. **E2e tests enhanced** (18e2bcd) - Added two more test cases on top of the existing `TestSkillDelete`:
   - `delete_again_fails`: verifies that deleting an already-deleted skill returns a non-zero exit code
   - `TestSkillDeleteNotFound`: verifies that the HTTP DELETE API returns 404 for a skill that was never published

All three e2e tests together cover: publish -> verify exists -> delete via CLI -> confirm 404 -> idempotent re-delete fails -> direct HTTP DELETE on non-existent returns 404.

File: internal/registry/api/handlers/v0/skills.go [hunk 1]
```diff
@@ -104,6 +104,34 @@ func RegisterSkillsEndpoints(api huma.API, pathPrefix string, registry service.R
...
+			return nil, huma.Error400BadRequest("Invalid skill name encoding", err)
+		}
+		version, err := url.PathUnescape(input.Version)
+		if err != nil {
+			return nil, huma.Error400BadRequest("Invalid version encoding", err)
+		}
+		if err := registry.DeleteSkill(ctx, skillName, version); err != nil {
+			if errors.Is(err, database.ErrNotFound) || errors.Is(err, auth.ErrForbidden) || errors.Is(err, auth.ErrUnauthenticated) {
+				return nil, huma.Error404NotFound("Skill not found")
+			}
```
Comment (inFocus7) [inline internal/registry/api/handlers/v0/skills.go]: recently we moved to returning actual error codes

```suggestion
			if errors.Is(err, database.ErrNotFound) {
				return nil, huma.Error404NotFound("Skill not found")
			}
			if errors.Is(err, auth.ErrUnauthenticated) {
				return nil, huma.Error401Unauthorized("Authentication required")
			}
			if errors.Is(err, auth.ErrForbidden) {
				return nil, huma.Error403Forbidden("Forbidden")
			}
```

File: e2e/skill_publish_test.go [hunk 2]
```diff
@@ -182,3 +183,95 @@ func TestSkillPublishDirectDryRun(t *testing.T) {
 	RequireOutputContains(t, result, "DRY RUN")
 	RequireOutputContains(t, result, "direct-test-skill")
 }
+
+// TestSkillDelete tests publishing a skill and then deleting it via the
+// DELETE /v0/skills/{name}/versions/{version} endpoint.
+func TestSkillDelete(t *testing.T) {
```
Comment (inFocus7) [inline e2e/skill_publish_test.go:480]: can we add a test that we correctly handle promoting a previously-published skill as latest when the current latest is deleted?

**Review by inFocus7 — COMMENTED** [review]
overall lgtm, two small requests and then it's good on my end

**Comment by optimus-fulcria** [comment]
Addressed both review items:

1. **Error codes** (per @inFocus7): Now returns proper HTTP status codes — `404` for not found, `401` for unauthenticated, `403` for forbidden — instead of lumping all into 404.

2. **Latest promotion test**: Added `TestSkillDeletePromotesLatest` — publishes v0.0.1 and v0.0.2, deletes v0.0.2 (current latest), then verifies "latest" resolves to v0.0.1.

**Comment by optimus-fulcria** [comment]
PR template updated, e2e tests added:
- `TestSkillDelete`: full publish → delete → verify 404 lifecycle
- `TestSkillDeleteNotFound`: verifies 404 on non-existent skill
- Latest version promotion tested when deleting the latest version

All CI checks pass. Ready for re-review.

**Comment by timflannagan** [comment]
(Had to force push to fix a merge conflict)
